import { Calligraffitti, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const calligraffitti = Calligraffitti({
  variable: "--font-calligraffitti",
  subsets: ["latin"],
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${calligraffitti.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
